name: 'Dependency Review'
on:
  push:
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Dependency Review (Pull Request)'
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: 'high' # This is your custom setting

      - name: 'Dependency Review (Manual)'
        if: github.event_name == 'workflow_dispatch'
        uses: actions/dependency-review-action@v4
        with:
          head-ref: ${{ github.ref }}
          base-ref: ${{ github.event.repository.default_branch }}
          fail-on-severity: 'high'
